### ISSUE TITLE
Task #1

### ISSUE THREAD

**Issue by arturpietrzak** [WikiKrolik/Image-Processing#1]
**Task 1: (all B, all G, N6, all E)**

Basic operations:
- [x] (B1) Image brightness modification (--brightness)
- [x] (B2) Image contrast modification (--contrast)
- [x] (B3) Negative (--negative)

Geometric operations:
- [x] (G1) Horizontal flip (--hflip)
- [x] (G2) Vertical flip (--vflip)
- [x] (G3) Diagonal flip (--dflip)
- [x] (G4) Image shrinking (--shrink)
- [x] (G5) Image enlargement (--enlarge)

Noise removal:
- [x] (N6) Median filter (--median),
- [x] (N6) Harmonic mean filter (--hmean)

Error analysis:
- [x] (E1) Mean square error (--mse)
- [x] (E2) Peak mean square error (--pmse)
- [x] (E3) Signal to noise ratio (--snr)
- [x] (E4) Peak signal to noise ratio (--psnr)
- [x] (E5) Maximum difference (--md)

Application
- [x] Add functionality to use as a command line program with parameters
- [x] Write report
