### ISSUE TITLE
Task #2

### ISSUE THREAD

**Issue by arturpietrzak** [WikiKrolik/Image-Processing#2]
**Task 2: (H3, all C, S6, O1)**

Histogram calculation:
- [x] Histogram creation (--histogram)
- [x] (H3) Raleigh final probability density function (--hraleigh)

Image characteristics:
- [x] (C1) Mean (--cmean)
- [x] (C1) Variance (--cvariance)
- [x] (C2) Standard deviation (--cstdev)
- [x] (C2) Variation coefficient I (--cvarcoi)
- [x] (C3) Asymmetry coefficient (--casyco)
- [x] (C4) Flattening coefficient (--cflaco)
- [x] (C5) Variation coefficient II (--cvarcoii)
- [x] (C6) Information source entropy (--centropy)

Linear image filtration:
- [x] (S6) Line identification (--slineid)

Non-linear image filtration:
- [x] (O1) Roberts operator I (--orobertsi)

Application:
- [x] Add new functions to the program from Task 1
- [x] Write report

**Comment by arturpietrzak** [comment]
```
public Bitmap Sobel(Bitmap image)
        {
            Bitmap processedImage = new Bitmap(image.Width, image.Height);

            for (int x = 1; x < image.Width - 1; x++)
            {
                for (int y = 1; y < image.Height - 1; y++)
                {
                    float xxR = image.GetPixel(x + 1, y - 1).R
                        + 2 * image.GetPixel(x + 1, y).R
                        + image.GetPixel(x + 1, y + 1).R
                        - image.GetPixel(x - 1, y - 1).R
                        - 2 * image.GetPixel(x - 1, y).R
                        - image.GetPixel(x - 1, y + 1).R;

                    float yyR = image.GetPixel(x - 1, y - 1).R
                        + 2 * image.GetPixel(x, y - 1).R
                        + image.GetPixel(x + 1, y - 1).R
                        - image.GetPixel(x - 1, y + 1).R
                        - 2 * image.GetPixel(x, y + 1).R
                        - image.GetPixel(x + 1, y + 1).R;

                    float xxG = image.GetPixel(x + 1, y - 1).G
                        + 2 * image.GetPixel(x + 1, y).G
                        + image.GetPixel(x + 1, y + 1).G
                        - image.GetPixel(x - 1, y - 1).G
                        - 2 * image.GetPixel(x - 1, y).G
                        - image.GetPixel(x - 1, y + 1).G;

                    float yyG = image.GetPixel(x - 1, y - 1).G
                        + 2 * image.GetPixel(x, y - 1).G
                        + image.GetPixel(x + 1, y - 1).G
                        - image.GetPixel(x - 1, y + 1).G
                        - 2 * image.GetPixel(x, y + 1).G
                        - image.GetPixel(x + 1, y + 1).G;

                    float xxB = image.GetPixel(x + 1, y - 1).B
                        + 2 * image.GetPixel(x + 1, y).B
                        + image.GetPixel(x + 1, y + 1).B
                        - image.GetPixel(x - 1, y - 1).B
                        - 2 * image.GetPixel(x - 1, y).B
                        - image.GetPixel(x - 1, y + 1).B;

                    float yyB = image.GetPixel(x - 1, y - 1).B
                        + 2 * image.GetPixel(x, y - 1).B
                        + image.GetPixel(x + 1, y - 1).B
                        - image.GetPixel(x - 1, y + 1).B
                        - 2 * image.GetPixel(x, y + 1).B
                        - image.GetPixel(x + 1, y + 1).B;

                    processedImage.SetPixel(x, y, Color.FromArgb(1,
                        (int)Math.Clamp(Math.Sqrt(xxR * xxR + yyR * yyR), 0, 255),
                        (int)Math.Clamp(Math.Sqrt(xxR * xxR + yyR * yyR), 0, 255),
                        (int)Math.Clamp(Math.Sqrt(xxR * xxR + yyR * yyR), 0, 255)));
                }
            }

            return processedImage;
        }
```
