### ISSUE TITLE
Task #3

### ISSUE THREAD

**Issue by arturpietrzak** [WikiKrolik/Image-Processing#3]
**Task 3: (M2, all R))**

Basic morphological operations:
- [x] dilation (--mdila)
- [x] erosion (--mero)
- [x] opening (--mopen)
- [x] closing (--mclos)
- [x] HMT transformation (--mhmt)
 
Specific variant:
- [x] (M2 prerequisite) complement
- [x] (M2 prerequisite) intersection
- [x] (M2 prerequisite) sum
- [x] (M2) Ask the user to choose any point p in image A and apply the following iterative operation... (--m2)

Image segmentation:
- [x] (R1) Region growing (--reggrow)

Application:
- [x] Add new functions to the program from Task 2
- [x] Write a report
