### ISSUE TITLE
Task #4

### ISSUE THREAD

**Issue by arturpietrzak** [WikiKrolik/Image-Processing#4]
**Task 4: (T2, all F)**

Fourier transform:
- [x] (T2) Slow discrete Fourier transform with decimation in frequency domain (--slowdft)
- [x] (T2) Slow inverse discrete Fourier transform with decimation in frequency domain
- [x] (T2) Fast discrete Fourier transform with decimation in frequency domain (--fastdft)
- [x] (T2) Fast inverse discrete Fourier transform with decimation in frequency domain
- [x] Visualization of Fourier spectrum

Filters in frequency domain:
- [x] (F1) Low-pass filter (high-cut filter) (--lpf)
- [x] (F2) High-pass filter (low-cut filter) (--hpf)
- [x] (F3) Band-pass filter (--bpf)
- [x] (F4) Band-cut filter (--bcf)
- [x] (F5) High-pass filter with detection of edge direction (--hpfded)
- [x] (F6) Phase modifying filter (--pmf)

Application:
- [x] Add new functions to the program from Task 3
- [x] Write a report
